local palette = {
  bg = "#101114",
  bg_dark = "#111318",
  bg_deep = "#0D0F12",
  bg_float = "#171A20",
  surface = "#252A33",
  surface_alt = "#303845",
  selection = "#202D3C",
  fg = "#D7DCE5",
  fg_dark = "#B4BFCE",
  fg_gutter = "#697486",
  primary = "#89A9C9",
  highlight = "#A9C4E4",
  cyan = "#79B7B8",
  green = "#9ECB8B",
  red = "#E58A93",
  yellow = "#FFC96B",
  purple = "#B79AD6",
  purple_bright = "#D0B7F0",
}

return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = false,
    priority = 1000,
    opts = {
      flavour = "mocha",
      term_colors = true,
      transparent_background = false,
      no_italic = true,
      dim_inactive = { enabled = false },
      integrations = {
        indent_blankline = {
          enabled = true,
          scope_color = "surface1",
          colored_indent_levels = false,
        },
        mini = {
          indentscope_color = "surface1",
        },
      },
      color_overrides = {
        mocha = {
          rosewater = "#C5CBD5",
          flamingo = "#B4BFCE",
          pink = palette.purple_bright,
          mauve = palette.purple,
          red = palette.red,
          maroon = "#D16D78",
          peach = palette.primary,
          yellow = palette.yellow,
          green = palette.green,
          teal = palette.cyan,
          sky = palette.highlight,
          sapphire = palette.primary,
          blue = palette.primary,
          lavender = palette.highlight,
          text = palette.fg,
          subtext1 = "#C5CBD5",
          subtext0 = palette.fg_dark,
          overlay2 = "#8993A3",
          overlay1 = palette.fg_gutter,
          overlay0 = "#5D6879",
          surface2 = palette.surface_alt,
          surface1 = palette.surface,
          surface0 = palette.bg_float,
          base = palette.bg,
          mantle = palette.bg_dark,
          crust = palette.bg_deep,
        },
      },
      highlight_overrides = {
        mocha = function(colors)
          return {
            Normal = { fg = colors.text, bg = colors.base },
            NormalNC = { fg = colors.subtext1, bg = colors.base },
            NormalFloat = { fg = colors.text, bg = colors.surface0 },
            FloatBorder = { fg = colors.surface2, bg = colors.surface0 },
            SignColumn = { bg = colors.base },
            CursorLine = { bg = colors.surface0 },
            CursorLineNr = { fg = colors.blue, bg = colors.surface0, bold = true },
            LineNr = { fg = colors.overlay1, bg = colors.base },
            StatusLine = { fg = colors.subtext1, bg = colors.surface0 },
            StatusLineNC = { fg = colors.overlay1, bg = colors.mantle },
            WinSeparator = { fg = colors.surface2, bg = colors.base },
            Search = { fg = colors.base, bg = colors.blue },
            IncSearch = { fg = colors.base, bg = colors.lavender },
            Visual = { bg = colors.blue0 or palette.selection },
            Pmenu = { fg = colors.text, bg = colors.surface0 },
            PmenuSel = { fg = colors.lavender, bg = colors.blue0 or palette.selection, bold = true },
            PmenuSbar = { bg = colors.surface1 },
            PmenuThumb = { bg = colors.overlay0 },
            Title = { fg = colors.blue, bold = true },
            MatchParen = { fg = colors.blue, bg = colors.surface0, bold = false },
            Constant = { fg = colors.lavender },
            Debug = { fg = colors.yellow },

            DiffAdd = { bg = "#1E3227" },
            diffAdded = { fg = colors.green, bg = "#1E3227" },
            DiffDelete = { fg = "#6B303A", bg = "#321D24" },
            diffRemoved = { fg = colors.red, bg = "#321D24" },
            DiffChange = { bg = colors.blue0 or palette.selection },
            diffChanged = { fg = colors.blue, bg = colors.blue0 or palette.selection },
            DiffText = { fg = colors.base, bg = colors.lavender, bold = true },

            DiffviewDiffDelete = { fg = "#6B303A", bg = "#321D24" },
            DiffviewDiffAddAsDelete = { fg = "#6B303A", bg = "#321D24" },
            DiffviewNormal = { fg = colors.text, bg = "#14171C" },
            DiffviewFilePanelTitle = { fg = colors.blue, bold = true },
            DiffviewFilePanelCounter = { fg = colors.blue, bold = true },
            DiffviewFilePanelFileName = { fg = colors.subtext1 },
            DiffviewFilePanelPath = { fg = colors.overlay1 },
            DiffviewFilePanelRootPath = { fg = colors.blue, bold = true },
            DiffviewFilePanelInsertions = { fg = colors.green },
            DiffviewFilePanelDeletions = { fg = colors.red },
            DiffviewStatusAdded = { fg = colors.green, bold = true },
            DiffviewStatusModified = { fg = colors.blue, bold = true },
            DiffviewStatusDeleted = { fg = colors.red, bold = true },
            DiffviewStatusRenamed = { fg = colors.mauve, bold = true },
            DiffviewStatusUntracked = { fg = colors.blue },
            DiffviewWinSeparator = { fg = colors.surface2, bg = "NONE" },
            DiffviewFolderSign = { fg = colors.blue },

            HerdrNvimCommentSign = { fg = colors.blue, bg = colors.base, bold = true },
            HerdrNvimCommentText = { fg = colors.lavender, bg = colors.surface0 },
            HerdrNvimCommentLine = { link = "CursorLine" },
            AgentReviewBorder = { fg = colors.surface2 },
            AgentReviewTitle = { fg = colors.lavender, bold = true },
            AgentReviewUser = { fg = colors.blue, bold = true },
            AgentReviewAgent = { fg = colors.green, bold = true },
            AgentReviewText = { fg = colors.subtext1 },
            AgentReviewTime = { fg = colors.overlay1 },

            MiniIconsOrange = { fg = colors.blue },
            MiniIconsYellow = { fg = colors.lavender },

            IblIndent = { fg = colors.surface0, nocombine = true },
            IblScope = { fg = colors.surface1, nocombine = true },
            IndentBlanklineChar = { fg = colors.surface0, nocombine = true },
            IndentBlanklineContextChar = { fg = colors.surface1, nocombine = true },
            MiniIndentscopeSymbol = { fg = colors.surface1, nocombine = true },
            MiniIndentscopePrefix = { fg = colors.surface0, nocombine = true },
            RainbowRed = { fg = colors.overlay1, nocombine = true },
            RainbowYellow = { fg = colors.blue, nocombine = true },
            RainbowBlue = { fg = colors.overlay1, nocombine = true },
            RainbowOrange = { fg = colors.overlay1, nocombine = true },
            RainbowGreen = { fg = colors.overlay1, nocombine = true },
            RainbowViolet = { fg = colors.overlay1, nocombine = true },
            RainbowCyan = { fg = colors.overlay1, nocombine = true },
            RainbowDelimiterRed = { fg = colors.overlay1 },
            RainbowDelimiterYellow = { fg = colors.blue },
            RainbowDelimiterBlue = { fg = colors.overlay1 },
            RainbowDelimiterOrange = { fg = colors.overlay1 },
            RainbowDelimiterGreen = { fg = colors.overlay1 },
            RainbowDelimiterViolet = { fg = colors.overlay1 },
            RainbowDelimiterCyan = { fg = colors.overlay1 },
            TSRainbowRed = { fg = colors.overlay1 },
            TSRainbowYellow = { fg = colors.blue },
            TSRainbowBlue = { fg = colors.overlay1 },
            TSRainbowOrange = { fg = colors.overlay1 },
            TSRainbowGreen = { fg = colors.overlay1 },
            TSRainbowViolet = { fg = colors.overlay1 },
            TSRainbowCyan = { fg = colors.overlay1 },
            TreesitterContext = { bg = colors.surface0 },
            TreesitterContextLineNumber = { fg = colors.overlay1, bg = colors.surface0 },
          }
        end,
      },
    },
    config = function(_, opts)
      require("catppuccin").setup(opts)
      vim.cmd.colorscheme("catppuccin-mocha")

      local terminal_colors = {
        palette.bg,
        "#D16D78",
        palette.green,
        "#D8A657",
        palette.primary,
        palette.purple,
        palette.cyan,
        "#C5CBD5",
        "#4E5665",
        palette.red,
        "#B7D99F",
        palette.yellow,
        palette.highlight,
        palette.purple_bright,
        "#99D5D2",
        "#F2F4F7",
      }
      for index, color in ipairs(terminal_colors) do
        vim.g["terminal_color_" .. (index - 1)] = color
      end
      vim.g.terminal_color_background = palette.bg
      vim.g.terminal_color_foreground = palette.fg
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin-mocha",
    },
  },
}
