return {
  {
    "echasnovski/mini.icons",
    opts = {
      file = {
        [".gitignore"] = { glyph = "󰊢", hl = "MiniIconsGrey" },
        ["package.json"] = { glyph = "󰏗", hl = "MiniIconsOrange" },
        ["pnpm-workspace.yaml"] = { glyph = "󰏗", hl = "MiniIconsYellow" },
        ["pnpm-lock.yaml"] = { glyph = "󰏓", hl = "MiniIconsYellow" },
        ["nuxt.config.ts"] = { glyph = "󱄄", hl = "MiniIconsGreen" },
        ["vite.config.ts"] = { glyph = "󱐋", hl = "MiniIconsYellow" },
        ["tsconfig.json"] = { glyph = "󰘐", hl = "MiniIconsAzure" },
        ["README.md"] = { glyph = "󰍔", hl = "MiniIconsCyan" },
        [".env"] = { glyph = "󰒓", hl = "MiniIconsYellow" },
        [".env.example"] = { glyph = "󰒓", hl = "MiniIconsGrey" },
      },
      extension = {
        vue = { glyph = "󰡄", hl = "MiniIconsGreen" },
        ts = { glyph = "󰘐", hl = "MiniIconsAzure" },
        tsx = { glyph = "󰘐", hl = "MiniIconsBlue" },
        js = { glyph = "󰌠", hl = "MiniIconsYellow" },
        jsx = { glyph = "󰌠", hl = "MiniIconsOrange" },
        json = { glyph = "󰈮", hl = "MiniIconsOrange" },
        yaml = { glyph = "󰋜", hl = "MiniIconsPurple" },
        yml = { glyph = "󰋜", hl = "MiniIconsPurple" },
        css = { glyph = "󰌜", hl = "MiniIconsBlue" },
        md = { glyph = "󰍔", hl = "MiniIconsCyan" },
        svg = { glyph = "󰜡", hl = "MiniIconsOrange" },
        png = { glyph = "󰋩", hl = "MiniIconsPurple" },
        jpg = { glyph = "󰋩", hl = "MiniIconsPurple" },
        webp = { glyph = "󰋩", hl = "MiniIconsPurple" },
      },
      directory = {
        app = { glyph = "󰀲", hl = "MiniIconsBlue" },
        components = { glyph = "󰅪", hl = "MiniIconsGreen" },
        composables = { glyph = "󰡱", hl = "MiniIconsAzure" },
        pages = { glyph = "󰈙", hl = "MiniIconsOrange" },
        assets = { glyph = "󰋩", hl = "MiniIconsPurple" },
        plugins = { glyph = "󰏗", hl = "MiniIconsYellow" },
        server = { glyph = "󰒋", hl = "MiniIconsCyan" },
        public = { glyph = "󰉐", hl = "MiniIconsGrey" },
        node_modules = { glyph = "󰏗", hl = "MiniIconsGrey" },
        [".git"] = { glyph = "󰊢", hl = "MiniIconsRed" },
      },
    },
  },
}
