unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-s

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key X kill-pane
bind-key -n S-Enter send-keys "\e[13;2u"

# Настройки Ghostty / Терминала
set -g mouse on
set -g default-terminal "tmux-256color"
set-option -g set-clipboard on
set -g focus-events on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g status-position top
set -g status-style "bg=#1e1e2e"
set -g @catppuccin_status_background "#1e1e2e"

# --- ИДЕАЛЬНЫЕ МОНОЛИТНЫЕ ПИЛЮЛИ ---
set -g @catppuccin_window_status_style "none" # Отключаем стандартный вывод

# Формат для НЕАКТИВНОГО окна (Surface0 фон, Text цвет текста)
set -g window-status-format "#[fg=#313244,bg=#1e1e2e]#[fg=#cdd6f4,bg=#313244]#I #W#[fg=#313244,bg=#1e1e2e]"

# Формат для АКТИВНОГО окна (Mauve фон, Crust цвет текста)
set -g window-status-current-format "#[fg=#cba6f7,bg=#1e1e2e]#[fg=#11111b,bg=#cba6f7,bold]#I #W#[fg=#cba6f7,bg=#1e1e2e]"

# Настройка ПИЛЮЛЬ справа (модули)
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

# Модули статус-бара
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -ag status-right "#(~/.config/tmux/scripts/layout_indicator.sh)"

# Индексы и интервалы
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g status-interval 1

# Авто-переименование
set-option -g allow-rename on
set-window-option -g automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"

# Initialize TMUX plugin manager
run '~/.config/tmux/plugins/tpm/tpm'
